const MODEL_URL="https://teachablemachine.withgoogle.com/models/szc0CyZF_/";
let model=null,maxPredictions=0,selectedCrop="",selectedFile=null,previewUrl=null,modelPromise=null;
const CROP_DATASET={"사과":["apple_scab","black_rot","cedar_apple_rust"],"옥수수":["corn_gray_leaf_spot","corn_common_rust","corn_northern_leaf_blight"],"포도":["grape_black_rot","grape_esca","grape_isariopsis_leaf_spot"],"귤":["citrus_greening"],"복숭아":["bacterial_spot"],"고추":["bacterial_spot"],"감자":["potato_early_blight","potato_late_blight"],"호박":["powdery_mildew"],"토마토":["bacterial_spot","tomato_early_blight","tomato_late_blight","tomato_leaf_mold","tomato_septoria_leaf_spot","tomato_target_spot","tomato_mosaic_virus","tomato_yellow_leaf_curl_virus"],"기타":[]};
const DISEASE_INFO={apple_scab:{label:"검은별무늬병",aliases:["검은별무늬병","apple_scab","apple scab","apple___apple_scab"]},black_rot:{label:"검은썩음병",aliases:["검은썩음병","black_rot","black rot","apple___black_rot","grape___black_rot"]},cedar_apple_rust:{label:"사과-향나무 녹병",aliases:["사과-향나무 녹병","cedar apple rust","apple___cedar_apple_rust"]},corn_gray_leaf_spot:{label:"회색잎반점병",aliases:["회색잎반점병","gray leaf spot","cercospora leaf spot","corn___cercospora_leaf_spot gray_leaf_spot"]},corn_common_rust:{label:"일반녹병",aliases:["일반녹병","common rust","corn___common_rust"]},corn_northern_leaf_blight:{label:"북방잎마름병",aliases:["북방잎마름병","northern leaf blight","corn___northern_leaf_blight"]},grape_esca:{label:"에스카병",aliases:["에스카병","esca","grape___esca"]},grape_isariopsis_leaf_spot:{label:"이사리옵시스 잎반점병",aliases:["이사리옵시스 잎반점병","isariopsis leaf spot","grape___leaf_blight (isariopsis leaf spot)"]},citrus_greening:{label:"감귤녹화병",aliases:["감귤녹화병","huanglongbing","citrus greening","orange___huanglongbing (citrus greening)"]},bacterial_spot:{label:"세균성 반점병",aliases:["세균성 반점병","bacterial spot"]},potato_early_blight:{label:"조기역병",aliases:["조기역병","early blight","potato___early_blight"]},potato_late_blight:{label:"역병",aliases:["역병","late blight","potato___late_blight"]},powdery_mildew:{label:"흰가루병",aliases:["흰가루병","powdery mildew","pumpkin___powdery_mildew"]},tomato_early_blight:{label:"조기역병",aliases:["tomato___early_blight"]},tomato_late_blight:{label:"역병",aliases:["tomato___late_blight"]},tomato_leaf_mold:{label:"잎곰팡이병",aliases:["잎곰팡이병","leaf mold","tomato___leaf_mold"]},tomato_septoria_leaf_spot:{label:"셉토리아 잎반점병",aliases:["셉토리아 잎반점병","septoria leaf spot","tomato___septoria_leaf_spot"]},tomato_target_spot:{label:"타깃반점병",aliases:["타깃반점병","target spot","tomato___target_spot"]},tomato_mosaic_virus:{label:"토마토 모자이크 바이러스병",aliases:["토마토 모자이크 바이러스병","tomato mosaic virus","tomato___tomato_mosaic_virus"]},tomato_yellow_leaf_curl_virus:{label:"토마토 황화잎말림 바이러스병",aliases:["토마토 황화잎말림 바이러스병","tomato yellow leaf curl virus","tomato___tomato_yellow_leaf_curl_virus"]}};
const HEALTH_ALIASES=["healthy","건강","정상","healthy leaf","apple___healthy","corn___healthy","grape___healthy","peach___healthy","pepper,_bell___healthy","potato___healthy","tomato___healthy","orange___healthy","pumpkin___healthy"];
const normalize=v=>String(v||"").toLowerCase().replace(/[|()[\]{}]/g," ").replace(/[—–-]/g," ").replace(/[_.]/g," ").replace(/\s+/g," ").trim();
const $=id=>document.getElementById(id);const els={status:$('model-status'),statusText:document.querySelector('#model-status .status-text'),upload:$('upload-area'),input:$('image-input'),choose:$('choose-image'),remove:$('remove-image'),previewWrap:$('preview-wrap'),preview:$('image-preview'),crops:$('crop-options'),analyze:$('analyze-btn'),note:$('action-note'),result:$('result-panel'),summary:$('result-summary'),crop:$('result-crop'),rule:$('result-rule'),warning:$('result-warning'),list:$('result-list'),raw:$('raw-list'),toast:$('toast')};
function status(state,text){els.status.dataset.state=state;els.statusText.textContent=text}function toast(m){els.toast.textContent=m;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),2500)}
async function loadModel(){status('loading','모델 준비 중…');try{modelPromise=tmImage.load(MODEL_URL+'model.json',MODEL_URL+'metadata.json');model=await modelPromise;maxPredictions=model.getTotalClasses();status('ready',`모델 준비 완료 · ${maxPredictions}개 클래스`);sync()}catch(e){console.error(e);status('error','모델을 불러오지 못했습니다');els.note.textContent='인터넷 연결을 확인한 뒤 새로고침해 주세요.'}}
function setCrop(c){selectedCrop=c;document.querySelectorAll('.crop-option').forEach(b=>{const on=b.dataset.crop===c;b.classList.toggle('selected',on);b.setAttribute('aria-checked',String(on))});sync()}
function sync(){els.analyze.disabled=!(selectedFile&&selectedCrop&&model);els.note.textContent=selectedFile&&selectedCrop&&model?`${selectedCrop} 잎 사진을 모델에 넣어 예측합니다.`:!selectedFile?'사진을 먼저 선택해 주세요.':!selectedCrop?'작물 종류를 선택해 주세요.':'모델 준비가 끝나면 분석할 수 있어요.'}
function handleFile(f){if(!f||!f.type.startsWith('image/'))return toast('이미지 파일만 올려주세요.');if(f.size>12*1024*1024)return toast('12MB 이하의 사진을 사용해 주세요.');if(previewUrl)URL.revokeObjectURL(previewUrl);selectedFile=f;previewUrl=URL.createObjectURL(f);els.preview.src=previewUrl;els.previewWrap.classList.remove('hidden');els.upload.classList.add('hidden');els.result.classList.add('hidden');sync()}
function clearFile(){if(previewUrl)URL.revokeObjectURL(previewUrl);selectedFile=null;previewUrl=null;els.input.value='';els.previewWrap.classList.add('hidden');els.upload.classList.remove('hidden');els.result.classList.add('hidden');sync()}
function diseaseKey(name){const n=normalize(name);for(const [key,info] of Object.entries(DISEASE_INFO))for(const a of info.aliases){const aa=normalize(a);if(n===aa||n.includes(aa)||aa.includes(n))return key}if(n.includes('black rot'))return'black_rot';if(n.includes('apple scab'))return'apple_scab';if(n.includes('cedar apple rust'))return'cedar_apple_rust';if(n.includes('gray leaf spot')||n.includes('cercospora leaf spot'))return'corn_gray_leaf_spot';if(n.includes('common rust'))return'corn_common_rust';if(n.includes('northern leaf blight'))return'corn_northern_leaf_blight';if(n.includes('esca'))return'grape_esca';if(n.includes('isariopsis leaf spot')||n.includes('leaf blight'))return'grape_isariopsis_leaf_spot';if(n.includes('huanglongbing')||n.includes('citrus greening'))return'citrus_greening';if(n.includes('bacterial spot'))return'bacterial_spot';if(n.includes('early blight'))return n.includes('tomato')?'tomato_early_blight':'potato_early_blight';if(n.includes('late blight'))return n.includes('tomato')?'tomato_late_blight':'potato_late_blight';if(n.includes('powdery mildew'))return'powdery_mildew';if(n.includes('leaf mold'))return'tomato_leaf_mold';if(n.includes('septoria leaf spot'))return'tomato_septoria_leaf_spot';if(n.includes('target spot'))return'tomato_target_spot';if(n.includes('tomato mosaic virus'))return'tomato_mosaic_virus';if(n.includes('tomato yellow leaf curl virus'))return'tomato_yellow_leaf_curl_virus';return null}
function health(name){const n=normalize(name);return HEALTH_ALIASES.some(a=>n===normalize(a)||n.endsWith(' '+normalize(a)))}
function label(name){if(health(name))return'건강 · 정상 잎';const k=diseaseKey(name);return k?DISEASE_INFO[k].label:name}
function adjust(pred,crop){const sorted=[...pred].sort((a,b)=>b.probability-a.probability),raw=sorted.slice(0,3);if(crop==='기타')return{items:raw,filtered:false,fallback:false};const allow=new Set(CROP_DATASET[crop]||[]),matched=sorted.filter(x=>{const k=diseaseKey(x.className);return k&&allow.has(k)}),healthy=sorted.filter(x=>health(x.className));if(matched.length)return{items:[...matched,...healthy].sort((a,b)=>b.probability-a.probability).slice(0,3),filtered:true,fallback:false};return{items:raw,filtered:false,fallback:true}}
const esc=s=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(pred){const a=adjust(pred,selectedCrop),raw=[...pred].sort((x,y)=>y.probability-x.probability).slice(0,3);els.result.classList.remove('hidden');els.crop.textContent=`선택 작물 · ${selectedCrop}`;els.rule.textContent=selectedCrop==='기타'?'원본 모델 TOP 3':a.filtered?'작물 데이터셋 우선':'원본 TOP 3 표시';els.summary.textContent=`${selectedCrop} 기준으로 모델의 실제 클래스명과 확률을 읽어 예측 결과를 정리했습니다.`;els.warning.className='result-warning hidden';if(selectedCrop==='기타'){els.warning.textContent='‘기타’는 작물별 필터 데이터가 없으므로 모델이 출력한 TOP 3를 그대로 표시합니다. 결과는 실제 병명과 다를 수 있습니다.';els.warning.classList.remove('hidden')}else if(a.fallback){els.warning.textContent='선택한 작물의 데이터셋과 일치하는 질병 클래스를 모델 출력에서 찾지 못했습니다. 원본 모델 TOP 3를 그대로 보여드리며, 실제 질병과 상이할 수 있음을 특히 주의해 주세요.';els.warning.classList.add('strong');els.warning.classList.remove('hidden')}else if(a.filtered){els.warning.textContent='작물별 질병 데이터셋과 모델 출력이 완전히 일치하지 않아, 선택한 작물에 해당하는 질병 정보를 점수보다 우선 반영했습니다. 따라서 원본 확률 순위와 최종 결과 순서가 달라질 수 있습니다.';els.warning.classList.add('adjusted');els.warning.classList.remove('hidden')}els.list.innerHTML=a.items.map((x,i)=>{const pct=Math.max(0,Math.min(100,x.probability*100));const k=diseaseKey(x.className);return`<div class="result-card"><div class="rank">${i+1}</div><div><div class="result-name">${esc(label(x.className))}</div><span class="result-origin">${k?'작물 데이터셋 병명 · ':''}모델 클래스: ${esc(x.className)}</span></div><div class="confidence"><strong>${pct.toFixed(1)}%</strong><div class="bar"><span style="width:${pct}%"></span></div></div></div>`}).join('');els.raw.innerHTML=raw.map((x,i)=>`<div class="raw-row"><span>${i+1}위 · ${esc(label(x.className))}</span><span>${(x.probability*100).toFixed(2)}%</span></div>`).join('');els.result.scrollIntoView({behavior:'smooth',block:'start'})}
async function predict(){if(!selectedFile||!selectedCrop)return;const old=els.analyze.innerHTML;els.analyze.disabled=true;els.analyze.innerHTML='<span>⏳</span><span>사진 분석 중…</span>';els.note.textContent='사진을 모델에 넣고 실제 예측값을 계산하고 있습니다.';try{if(!model)await modelPromise;const url=URL.createObjectURL(selectedFile),img=new Image();img.src=url;await img.decode();const p=await model.predict(img);URL.revokeObjectURL(url);render(p);els.note.textContent='분석이 완료되었습니다. 결과는 예측 보조정보로 활용하세요.'}catch(e){console.error(e);toast('분석 중 오류가 발생했습니다. 사진을 다시 선택해 주세요.');els.note.textContent='분석에 실패했습니다.'}finally{els.analyze.innerHTML=old;sync()}}
els.choose.onclick=e=>{e.stopPropagation();els.input.click()};els.upload.onclick=()=>els.input.click();els.upload.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();els.input.click()}};els.input.onchange=e=>handleFile(e.target.files?.[0]);els.remove.onclick=clearFile;['dragenter','dragover'].forEach(t=>els.upload.addEventListener(t,e=>{e.preventDefault();els.upload.classList.add('dragover')}));['dragleave','drop'].forEach(t=>els.upload.addEventListener(t,e=>{e.preventDefault();els.upload.classList.remove('dragover')}));els.upload.addEventListener('drop',e=>handleFile(e.dataTransfer?.files?.[0]));els.crops.onclick=e=>{const b=e.target.closest('.crop-option');if(b)setCrop(b.dataset.crop)};els.analyze.onclick=predict;loadModel();
